language: python
python:
    - "3.5"
install: true
before_script:
    - git config --global user.email "tomas@getadblock.com"
    - git config --global user.name "Tomáš Taro"
    - git remote rm origin
    - git remote add origin https://${GH_TOKEN}@github.com/CatBlock/catblock.git
    - pip install selenium
script:
    - python tools/make_release.py -b firefox -ext y
    - python tools/make_release.py -b edge
    - python tools/make_release.py -b chrome
    - python tools/make_release.py -b opera
after_success:
    - cd tools/
    - chmod +x ./publish_release.sh
    - ./publish_release.sh
deploy:
  provider: releases
  api_key:
    secure: EM9LkwJDLAvva2FTvNmq9gUi/OOi2BE5h2LLtTfV/VLUydEShvlq2RZn9S6MEzcvFssaMbuQWwCX2RQ06Wq3OaCZOE3/LivTp6QIJhW/MqPwUgSOZ4CFyKU5WDDK1EZBaSN6oJHZCwn9MuMJc5hoYkT7SAk2kd4qM40/RaMeoNorbr+1z3dreUcCPTXEJxfUCBVNr+n6PF+hLOtcTX86COfZGkPGftmh4+z7ffSIRg3FnQzY60G9JVmlGj74K2bTOywUBAnh0xjIXoBoFIh7FTCyOUIsfZHQzQov0dBpU7NFX4wj735NDkN5XkgvTQQ66LQ5DwizECZJU0NyRznLPJ+Pxs6J1wMXsUB+8dM6c4FTJiOU0roW4S/jmnMzI7Q8BiynYwPBxNcAJmbcd+kYDP2cwyWyKYQROHGcMpo/pTVyUsrIOe1rKhS3RBEcqB7wuZmypNPa2adkRPwp4y7nuIn7F5GI3c7e8kp7l1X9wp4VJHaxD+j+baEfJSz5ueHGOSn0nqV2EBUiu3BqCUxakVCWVvSpXXiW7bz1KPxv3sANxkUaytAOxF597GgGqKmI59RXdY93LSR47/3YEqN8HBaeOmClsHITWma/P8rqSSFNzr+kH70NOCyUzdI7+9Aan4ddbOdDDmmbF6hSMP6sYlgyBNqte9bNRU4SDiflHy0=
  file:
    - "builds/catblock-firefox.xpi"
    - "builds/catblock-edge.zip"
    - "builds/catblock-chrome.zip"
    - "builds/catblock-opera.zip"
  skip_cleanup: true
  on:
    repo: CatBlock/catblock
    tags: true
    all_branches: true
notifications:
  slack: catblock:FcjzLmw4Kr0pU0vwE97pT52m